### ISSUE TITLE
Compile error with MLIR from source

### ISSUE THREAD

**Issue by vfdev-5** [vasily-v-ryabov/phdays24#1]
Hey @vasily-v-ryabov , thanks for this repo and the talk you gave on phdays, very helpful for beginners. 
While compiling `01_MLIR_gen` example using LLVM/MLIR from source ([dfc3494d48f0](https://github.com/llvm/llvm-project/commit/dfc3494d48f06be9144b9a1d5cb76e519c194215)), this code gives an error:
https://github.com/vasily-v-ryabov/phdays24/blob/1076ddb6fc2ebbd30d81bec32d49b2fd791d4373/01_MLIR_gen/main.cpp#L25

```
In file included from /llvm-project/mlir/include/mlir/Dialect/LLVMIR/LLVMDialect.h:91,
                 from /phdays24/01_MLIR_gen/main.cpp:11:
/llvm-project/build-rel-debug-info/tools/mlir/include/mlir/Dialect/LLVMIR/LLVMOps.h.inc:12863:10: note: candidate: 'mlir::Block* mlir::LLVM::LLVMFuncOp::addEntryBlock(mlir::OpBuilder&)'
12863 |   Block *addEntryBlock(OpBuilder &builder);
```

Seems like they now require to pass builder to the function. Adding the function, compilation succeeded:
```c++
mlir::Block *entryBlock = mainFunc.addEntryBlock(builder);
```

**Comment by vasily-v-ryabov** [comment]
Thanks for the report! I made archive branch `mlir-18.x` and updated `main` branch for use of LLVM-19.x including `install.sh` script.

**Comment by vasily-v-ryabov** [comment]
Sorry for few force pushes to `main` branch :) I fixed README as well.

**Comment by vfdev-5** [comment]
No problems at all, thanks for fixing it!
